#!/bin/bash
#
# create layout for java project
# YourProjectName/
# comment block with : <<'END';
: <<'END'
${javaProjectName}
├── src/
│   ├── main/
│   │   ├── java/
│   │   │   ├── package1/
│   │   │   │   └── Class1.java
│   │   │   ├── package2/
│   │   │   │   └── Class2.java
│   │   │   └── Main.java
│   │   └── resources/
│   └── test/
│       ├── java/
│       │   ├── package1/
│       │   │   └── Class1Test.java
│       │   ├── package2/
│       │   │   └── Class2Test.java
│       │   └── MainTest.java
│       └── resources/
├── lib/
│   ├── dependency1.jar
│   └── dependency2.jar
├── build/
├── dist/
├── docs/
└── README.md
END

echo "run file "

javaProjectName=$1

mkdir -p "${javaProjectName}/{src,test,lib,build,dist,docs}"
mkdir -p "${javaProjectName}/src/{main,test}/"
touch "${javaProjectName}/README.md"

touch "${javaProjectName}/src/main/Main.java"
echo "public class Main {
    public static void main(String[] args) {
        // Program execution starts here
        System.out.println(\"Hello, world!\");
    }
}
" >>"${javaProjectName}/src/main/Main.java"

cd "${javaProjectName}/src/main"
nvim "${javaProjectName}.java"
